diff --git a/config/cucumber.yml b/config/cucumber.yml
index 621a14c..c9fd356 100644
--- a/config/cucumber.yml
+++ b/config/cucumber.yml
@@ -6,3 +6,5 @@ std_opts = "--format #{ENV['CUCUMBER_FORMAT'] || 'progress'} --strict --tags ~@w
 default: <%= std_opts %> features
 wip: --tags @wip:3 --wip features
 rerun: <%= rerun_opts %> --format rerun --out rerun.txt --strict --tags ~@wip
+autotest-all: --format progress --color
+autotest: --format pretty --color
