diff --git a/config/newrelic.yml b/config/newrelic.yml
index 01fdedd..98a3cd9 100644
--- a/config/newrelic.yml
+++ b/config/newrelic.yml
@@ -189,7 +189,7 @@ common: &default_settings
 development:
   <<: *default_settings
   # Turn on communication to New Relic service in development mode
-  monitor_mode: true
+  monitor_mode: false
   app_name: <%= @app_name %> (Development)
 
   # Rails Only - when running in Developer Mode, the New Relic Agent will
@@ -197,7 +197,7 @@ development:
   # executed since starting the mongrel.
   # NOTE: There is substantial overhead when running in developer mode.
   # Do not use for production or load testing.
-  developer_mode: false
+  developer_mode: true
 
   # Enable textmate links
   # textmate: true
